export {default as DashboardContent } from './DashboardPage'
export {default as MemberContent } from './Member/MemberPage'
export {default as SalesContent } from './SalesPage'
export {default as PromoPage } from './Promo/PromoPage'
export {default as ProductPage } from './Product/ProductPage'
export {default as ReservationPage } from './Reservation/ReservationPage'
