export {default as DashboardContent } from './DashboardPage'
export {default as MemberContent } from './Member/MemberPage'
export {default as ClientPage } from './ClientPage'
export {default as SalesContent } from './SalesPage'
export {default as PromoPage } from './PromoPage'
export {default as ProductPage } from './ProductPage'
export {default as ReservationPage } from './ReservationPage'
